### ISSUE TITLE
Any plan to have it on AUR

### ISSUE THREAD

**Issue by dickoa** [JanMarvin/v8-R#2]
Hi Marvin,
Thanks a lot for maintaining this build of v8, it's really helpful.
I wanted to check with you if pushing this to AUR is on your roadmap ? And let me know if I can help, I never pushed a PKGBUILD on AUR but this one is really valuable to the R community so I'm willing to help if needed.
Thanks again

**Comment by JanMarvin** [comment]
Hey Ahmadou,
thanks for your kind words and asking for the AUR update. I've given it some thought and will push it to the AUR over the weekend. The process is actually quite simple and I've maintained packages before. Though I currently do not have the privilege anymore to run Arch at work. This complicates the maintenance process a bit as I don't see if e.g. icu updates break the package. I leave this issue open and please feel free to remind me, if I forget about it.
Marvin

**Comment by dickoa** [comment]
Thanks a lot @JanMarvin. I tried to build v8 using the latest commit but I have some errors. 
I will see if I can fix it and make PR, in the meatinme I will create another issue with the error message I currently have.
Ahmadou

**Comment by JanMarvin** [comment]
Hey @dickoa the package is in the AUR at https://aur.archlinux.org/packages/v8-r/

**Comment by dickoa** [comment]
Wow that's really awesome @JanMarvin. I will share the link on this thread https://github.com/ropensci/geojsonio/issues/143.
Thanks again for the great work.
