### ISSUE TITLE
makepkg fails

### ISSUE THREAD

**Issue by znmeb** [JanMarvin/v8-R#3]
See attached log file
[build-fail.txt](https://github.com/JanMarvin/v8-R/files/3612286/build-fail.txt)

**Comment by JanMarvin** [comment]
Thanks for the report @znmeb. It's due to the python changes I made. I thought that the Google depot tools were python 3 ready, but they are somehow not. Kinda strange though, that it works on my system.

**Comment by JanMarvin** [comment]
I've reverted some changes, should be fixed now

**Comment by znmeb** [comment]
Google doesn't have much time left to make their depot tools "Python 3 ready" - Python 2 has about 3 months left to live and fixing code always takes longer than they think it should. ;-)
